import Intro from "./intro";
import Loader from "./loader";
import Auth from "./auth-form";
import Header from "./header";
import Features from "./features";
import Footer from "./footer/inder";
import Dashboard from "./dashboard";
import Transformer from "./transformer";
import FormGenerator from "./form-generator";
import Boundry from "./auth-boundry";
import Survey from "./survey";
export { Header, Footer, Intro, Features, Auth, FormGenerator, Transformer, Dashboard, Boundry, Loader, Survey };